version: "3"
services:
  redis-cluster:
    image: redis/redis-stack-server:6.2.2-v5
    container_name: redis-master-7001
    networks:
      app_net:
        ipv4_address: 172.24.1.1
    volumes: # 작성한 설정 파일을 볼륨을 통해 컨테이너에 공유
      - ./redis_7001.conf:/etc/redis-stack.conf
      - ./logs:/data/redis
    command: redis-server /etc/redis-stack.conf
    ports:
      - 7001:7001
      - 17001:17001

  redis-node-1:
    image: redis/redis-stack-server:6.2.2-v5
    container_name: redis-master-7002
    networks:
      app_net:
        ipv4_address: 172.24.1.2
    volumes:
      - ./redis_7002.conf:/etc/redis-stack.conf
      - ./logs:/data/redis
    command: redis-server /etc/redis-stack.conf
    ports:
      - 7002:7002
      - 17002:17002

  redis-node-2:
    image: redis/redis-stack-server:6.2.2-v5
    container_name: redis-master-7003
    networks:
      app_net:
        ipv4_address: 172.24.1.3
    volumes:
      - ./redis_7003.conf:/etc/redis-stack.conf
      - ./logs:/data/redis
    command: redis-server /etc/redis-stack.conf
    ports:
      - 7003:7003
      - 17003:17003

  redis-node-3:
    image: redis/redis-stack-server:6.2.2-v5
    container_name: redis-slave-7004
    networks:
      app_net:
        ipv4_address: 172.24.1.4
    volumes:
      - ./redis_7004.conf:/etc/redis-stack.conf
      - ./logs:/data/redis
    command: redis-server /etc/redis-stack.conf
    ports:
      - 7004:7004
      - 17004:17004

  redis-node-4:
    image: redis/redis-stack-server:6.2.2-v5
    container_name: redis-slave-7005
    networks:
      app_net:
        ipv4_address: 172.24.1.5
    volumes:
      - ./redis_7005.conf:/etc/redis-stack.conf
      - ./logs:/data/redis
    command: redis-server /etc/redis-stack.conf
    ports:
      - 7005:7005
      - 17005:17005

  redis-node-5:
    image: redis/redis-stack-server:6.2.2-v5
    container_name: redis-slave-7006
    networks:
      app_net:
        ipv4_address: 172.24.1.6
    volumes:
      - ./redis_7006.conf:/etc/redis-stack.conf
      - ./logs:/data/redis
    command: redis-server /etc/redis-stack.conf
    ports:
      - 7006:7006
      - 17006:17006

  redis-node-6:
    image: redis/redis-stack-server:6.2.2-v5
    container_name: redis-slave-7007
    networks:
      app_net:
        ipv4_address: 172.24.1.7
    volumes:
      - ./redis_7007.conf:/etc/redis-stack.conf
      - ./logs:/data/redis
    command: redis-server /etc/redis-stack.conf
    ports:
      - 7007:7007
      - 17007:17007

  redis-node-7:
    image: redis/redis-stack-server:6.2.2-v5
    container_name: redis-slave-7008
    networks:
      app_net:
        ipv4_address: 172.24.1.8
    volumes:
      - ./redis_7008.conf:/etc/redis-stack.conf
      - ./logs:/data/redis
    command: redis-server /etc/redis-stack.conf
    ports:
      - 7008:7008
      - 17008:17008

  redis-node-8:
    image: redis/redis-stack-server:6.2.2-v5
    container_name: redis-slave-7009
    networks:
      app_net:
        ipv4_address: 172.24.1.9
    volumes:
      - ./redis_7009.conf:/etc/redis-stack.conf
      - ./logs:/data/redis
    command: redis-server /etc/redis-stack.conf
    ports:
      - 7009:7009
      - 17009:17009

  redis-cluster-entry:
    image: redis/redis-stack-server:6.2.2-v5
    container_name: redis-cluster-entry
    networks:
      app_net:
        ipv4_address: 172.24.1.10
    command: redis-cli --cluster create 172.24.1.1:7001 172.24.1.2:7002 172.24.1.3:7003 172.24.1.4:7004 172.24.1.5:7005 172.24.1.6:7006 172.24.1.7:7007 172.24.1.8:7008 172.24.1.9:7009 --cluster-yes --cluster-replicas 2
    depends_on:
      - redis-cluster
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
      - redis-node-5
      - redis-node-6
      - redis-node-7
      - redis-node-8

networks:
  app_net:
    ipam:
      driver: default

      config:
        - subnet: 172.24.0.0/16
          gateway: 172.24.0.1
